# FUNDING.yml
github: # GitHub Sponsors
  sponsors:
    - username: Cod3xDev
  tiers:
    - name: Bronze
      description: A small token of appreciation
      monthly_amount: 5
    - name: Silver
      description: Showcasing our gratitude
      monthly_amount: 10
    - name: Gold
      description: Making a significant impact
      monthly_amount: 20

btc: "1P4GBec8U8uJ7MEVL1ka6oYkcSZMrz3M7H"
eth: "0x66f11096a3779189dfc1d41e7453342576079469"
ltc: "MQX6cMcGM4Ck5sTjZF8uaPcbEDX7BAmtGW"
bch: "qpfwg92dvray6q9nywr3p9uettc50a709yn74r44lh"

kofi: "https://ko-fi.com/cod3xdev"
guilded: "https://www.guilded.gg/Cod3xDev/subscriptions"
